spring:
  profiles:
    include:
      # application-secrets.yaml
      - secrets
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      #ddl-auto: update
      ddl-auto: create-drop
  datasource:
    # URL, username and password are defined in application-secrets.yaml
    # URL:
    # username:
    # password:
    platform: postgres
    driver-class-name: org.postgresql.Driver
server:
  port: 8081